language: android
sudo: true
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra

script: gradle build lint test

before_install:
  - pip install codecov
after_success:
  - codecov
after_failure:
- cat app/build/outputs/lint-results.xml
- cat app/build/reports/tests/debug/index.html
